Channel:
  Start: 6  
  End: 6
  Steps: 1

# Ch 6 = TACTOR 1 for FOT - Brown-White
# Ch 5 = TACTOR 2 for IFNFN (REMOVED NIPPLE) - Blue

Volume:
  Start: 100     
  End: 100
  Steps: 10

Frequency:
  Start: 42
  End: 42
  Steps: 2

# See docs\protocol\42Hz test stim freq why.md for why 42 Hz.

# | Marker | Description | Phase |
# | :--- | :--- | :--- |
# | **3** | Baseline 1: VHP OFF/ON transition | Calibration |
# | **31** | Baseline 2: Stim ON (No physical contact) | Calibration |
# | **33** | Baseline 2: Stim OFF (No physical contact) | Calibration |
# | **333** | Baseline 3: Pre-Sweep Rest (Physical contact) | Recording |
# | **0** | Trial Rest (Inter-stimulus interval) | Recording |
# | **1** | Trial Stimulation ON | Recording |
# | **11** | Trial Stimulation OFF (Recovery) | Recording |

Baselines:
  Baseline_1: 3
  Baseline_2: 4
  Baseline_3: 5

Measurements:
  Number: 50 # should be 50-100, 3 is for testing
  Duration_on: 5
  Duration_off: 2
